### PR TITLE
Add Tray Menu

### PR DESCRIPTION
**Pull request by Nightblade**
I can *never* remember the hotkeys for this script!

### CODE REVIEW

**Comment by coldino** [comment]
Looks like a fine addition. I should be able to test this later ready for merge.

Maybe you could also throw in a hotkey reminder window with another tray menu item to open it? 😁

**Comment by Nightblade** [comment]
Aww shucks, thanks  😁

> Maybe you could also throw in a hotkey reminder window with another tray menu item to open it? 😁

Or, perhaps append the key combo to the tray menu items?

**Comment by coldino** [comment]
Sorry for the delay. This is merged with just a minor reduction in wording on the menu itself to reduce the width. Thanks very much.

I'd be very happy to get keyboard shortcuts on the menu. The AHK language gives me the cold sweats, so any and all contributions are very welcome!

**Comment by Nightblade** [comment]
No need to apologise ;)

Yeah it gives me the sweats too lol!

**Pull request merged**
